### ISSUE TITLE
Output name when generating a single diagram

### ISSUE THREAD

**Issue by FabAlchemy** [mermaid-js/mermaid-cli#355] opened 2022-08-16 09:08 UTC
**Describe the bug**
Introduced in 9.1.5: when the input file contains only one diagram, the output file name is different from the requested name.

**To Reproduce**

1. Create a Markdown file with exactly one graph.

````markdown
<!-- file: test.md -->
```mermaid
flowchart
    A
```
````

2. Generate the graph with a specific output file name:

```console
$ docker run --rm -it -u $UID -v $(pwd):/data:rw minlag/mermaid-cli -i /data/test.md -o /data/test.pdf
Found 1 mermaid charts in Markdown input
✅ /data/test-1.pdf
```

**Expected behavior**
When the input file only contains one graph, the output file name should be the one provided, without the number suffix (this was the behavior in 9.1.4).

```console
$ docker run --rm -it -u $UID -v $(pwd):/data:rw minlag/mermaid-cli:9.1.4 -i /data/test.md -o /data/test.pdf
Found 1 mermaid charts in Markdown input
✅ /data/test.pdf
```

**Comment by aloisklink** [comment] 2022-08-16 19:05
Caused by #351 (side-note, 9.1.5 still uses the old behaviour, it's the `9.1.6-beta*` images that use the new behaviour)

Thanks for reporting this (especially since your bug report is very detailed)! Unfortunately, in my opinion, this is not a bug, and this is instead expected behaviour.

The old behaviour was due to a bug in 9.1.3 (see https://github.com/mermaid-js/mermaid-cli/commit/e38fd34e4eb3b0fd4149b6348aabd9b72c50ee91 and https://github.com/mermaid-js/mermaid-cli/issues/348), which broke using `.md` as an input and `.svg`/`.pdf` as output. (`.png` used the correct behaviour).

If you run your command with `minlag/mermaid-cli:9.1.2`, you'll see the correct behaviour.

If you run your command with `minlag/mermaid-cli:9.1.4`, you'll also see the correct behaviour when using `-o test.png`.

> When the input file only contains one graph, the output file name should be the one provided, without the number suffix (this was the behavior in 9.1.4).

Unfortunately, if we do change this, this will break people's code if they are upgrading from 9.1.2 or earlier, or if anybody is using `-o test.png`. On the plus side, #351 adds some tests for this case, so this behaviour shouldn't change in the future.

**I'll vote to close this as a "Expected behaviour - won't fix".**

**Comment by MindaugasLaganeckas** [comment] 2022-08-18 10:19
I will close the case based on the comments above.

**Closed by MindaugasLaganeckas** 2022-08-18 10:19 UTC
