### ISSUE TITLE
mmdc incorrectly converts <br/> to <br> in SVG output

### ISSUE THREAD

**Issue by vdvleon** [mermaid-js/mermaid-cli#110] opened 2021-03-19 09:39 UTC
**Describe the bug**
When converting a .mmd file to a .svg file, XHTML style elements (e.g. `<br />`) are incorrectly converted to HTML 5 style elements (e.g. `<br>`).  This breaks SVG rendering in browsers.

Workaround used:
```
sed -i tmp 's#<br>#<br/>#g' test.svg
```

**To Reproduce**

1. Considering the file `test.mmd` with the following contents:
   ```
   graph LR
     a --> |"line 1<br />line 2"| b
   ```

2. Run `npx mmdc --input test.mmd --output test.svg`

**Expected behavior**
Expected is a SVG file with a `<br />` tag.

**Actual behavior**
A SVG file with a `<br>` tag, which is incorrect in SVG.

**Desktop (please complete the following information):**

- OS: macOS 11.2.2
- Version `@mermaid-js/mermaid-cli`: `^8.9.0`

**Comment by MindaugasLaganeckas** [comment] 2021-03-23 07:29
Duplicate of #74

**Closed by MindaugasLaganeckas** 2021-03-23 07:29 UTC
