### ISSUE TITLE
mmdc truncate content when outputFormat is png

### ISSUE THREAD

**Issue by eval-exec** [mermaid-js/mermaid-cli#463] opened 2023-01-13 08:01 UTC
**Describe the bug**
mmdc will truncate content when outputFormat is png

**To Reproduce**

1. create a file named `file.mermaid`: 
```
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```
3. execute : ` mmdc -i file.mermaid -s 10 -e png`
4. open generated file: `file.mermaid.png`
5. you can see in right-down conor of work `Car`, the letter `r` not display well, seems to be truncated.

**Expected behavior**
mermaid content shouldn't be truncated

**Screenshots**
![file mermaid](https://user-images.githubusercontent.com/46400566/212268360-f4e2f789-b461-4a44-b3d4-03709c879fc3.png)
**Desktop (please complete the following information):**

- OS: Linux 6.1.4-arch1-1
- Browser chrome
- Version: mmdc's version: 9.3.0

**Additional context**
When I specify outputFormat to svg, mmdc work well as expected.

**Comment by aloisklink** [comment] 2023-05-30 00:13
Duplicate of https://github.com/mermaid-js/mermaid-cli/issues/539

**Comment by aloisklink** [comment] 2023-05-30 00:13
Normally I'd close newer issues over the older issue, but issue #539 has more information explaining that this bug is due to font-awesome icons, so I'm going to close this issue in favor of that one.

Thanks @eval-exec for reporting this :smile:, feel free to subscribe to #539 if you want more information (or see https://github.com/mermaid-js/mermaid/issues/2651 for the upstream bug).

**Closed by aloisklink** 2023-05-30 00:13 UTC
