### ISSUE TITLE
Mermaid CLI exe for Windows

### ISSUE THREAD

**Issue by Stephanevg** [mermaid-js/mermaid-cli#570] opened 2023-07-22 05:52 UTC
**Is your feature request related to a problem? Please describe.**
This basically follows the discussions open https://github.com/mermaid-js/mermaid-cli/issues/467 and https://github.com/mermaidjs/mermaid.cli/issues/73

In a nutshell, it would be great to have a standard way of releasing a format that could be installed easily on Windows. 

**Describe the solution you'd like**
One suggestion would be to create an .exe / .msi which would be attached to the project as a release.

**Describe alternatives you've considered**

The current path of doing this would be to do this https://github.com/mermaid-js/mermaid-cli/issues/467#issuecomment-1483919459

Additionally, nodes.js needs to be installed first, followed by the installation of npm, than the steps above will take place

**Additional context**
This would really simply how windows users get access to the library, and would open up doors for potential new projects that need this on Windows machines.

**Comment by aloisklink** [comment] 2023-07-23 01:49
Duplicate of #467

**Closed by aloisklink** 2023-07-23 01:49 UTC
