### ISSUE TITLE
Is there a way to download chromium once?

### ISSUE THREAD

**Issue by Gryhyphen** [mermaid-js/mermaid-cli#51] opened 2020-09-16 02:44 UTC
I'm hoping it's possible to get the mermaid cli tool to not download Chromium r800071 every time I run `npx -p @mermaid-js/mermaid-cli mmdc` .

I'm scratching my head a bit because it feels like it's something that should be possible, but I don't really know how.

It would save me like 20-30 seconds per time I run the command if it just kept a copy of it around somewhere.

I'm on windows. Any help would be appreciated!

**Comment by MindaugasLaganeckas** [comment] 2020-10-01 09:19
Unfortunately, I do not have any input. If you find a way, please, share via PR :smile:

**Comment by BastianZim** [comment] 2020-11-24 13:00
Just as an FYI.

Puppeteer can skip the download through [env variables](https://github.com/puppeteer/puppeteer/blob/v5.5.0/docs/api.md#environment-variables) but this is not the standard approach as outlined [here](https://www.npmjs.com/package/puppeteer#installation):

> When you install Puppeteer, it downloads a recent version of Chromium (~170MB Mac, ~282MB Linux, ~280MB Win) that is guaranteed to work with the API. To skip the download, or to download a different browser, see Environment variables.

**Comment by MindaugasLaganeckas** [comment] 2022-10-02 11:56
Duplicate of #331

**Closed by MindaugasLaganeckas** 2022-10-02 11:56 UTC
