### ISSUE TITLE
File naming not correct when generating png images for multiple .md files 

### ISSUE THREAD

**Issue by hartmanjan1970** [mermaid-js/mermaid-cli#425] opened 2022-11-11 11:56 UTC
My goal is to automate generation of images from the diagrams.
If i use `mmdc -e png -i ./site/mermaid/*.md` 
Then for all .md files in the folder the images are generated content wise correctly as png but the file is called `myfile.md-1.svg` 
Is there some other way to get this working or is this a bug?

secondly i have a question for output file placement: Is there a way to define an output folder to place the generated images?

thanks

**Comment by aloisklink** [comment] 2022-11-12 19:51
> My goal is to automate generation of images from the diagrams.
> If i use mmdc -e png -i ./site/mermaid/*.md
> Then for all .md files in the folder the images are generated content wise correctly as png but the file is called myfile.md-1.svg
> Is there some other way to get this working or is this a bug?

Duplicate of https://github.com/mermaid-js/mermaid-cli/issues/394

It is a bug. It's been fixed on the `master` branch, but it hasn't yet been officially published. This project tries to follow the main [mermaid](https://github.com/mermaid-js/mermaid) version numbering scheme, so we try to bundle minor bug-fixes/features with mermaid updates. There's just recently been a mermaid release, so there will probably be a new mermaid-cli release very soon!

> secondly i have a question for output file placement: Is there a way to define an output folder to place the generated images?

I believe they're put in the same folder as the generated markdown file, so you can decide that by adding `--output ./my/directory/structure/my-output-file.md` and your output should appear as:
- `./my/directory/structure/my-output-file.md` (markdown file)
- `./my/directory/structure/my-output-file.md-1.svg` (image 1)
- `./my/directory/structure/my-output-file.md-2.svg` (image 2)
- ...etc.

If you mean that you want them in a separate directory from the markdown file, that's currently not supported, but you're welcome to make a new GitHub Issue as a feature request.

You may find other mermaid markdown-renderer specific plugins like https://github.com/raghur/mermaid-filter more useful, as this project tries not to use syntax specific to a single Markdown renderer, unlike other projects.

**Closed** 2022-11-12 19:51 UTC

**Comment by aloisklink** [comment] 2022-11-12 19:53
Duplicate of https://github.com/mermaid-js/mermaid-cli/issues/394
